### ISSUE TITLE
"org_id" fehlt / missing

### ISSUE THREAD

**Issue by WirArbeitenMitHochdruckAnEinerLoesung** [kennymc-c/vaultwarden-lang-de#8]
Hallo!

Es scheint ein Problem mit der Variable "org_id" zu geben, die in der Datei "send_org_invite.html.hbs" nicht erkannt wird. Ist hier seit dem letzten Vaultwarden-Update eine Änderung eingetreten, die übernommen werden müsste?

Es konnten keine Einladungen mehr verschickt werden. Nach dem Zurückgehen auf das Original-Template funktionierte das Einladen wieder.

---------------------------------------------

There seems to be a problem regarding "org_id" which is reported as missing in the logs while trying to send invitation emails. New Users cannot be invited anymore using this template. Error: "Handlebars".

File: "send_org_invite.html.hbs"

After rolling back to the default english template invites can be send again.

**Comment by strausmann** [comment]
Ah, dieses Problem hatte ich auch schon bemerkt. Aber nur den Fehler Handlebars bekommen, aber nicht welches Problem es verursacht.

Ich kann aber im Original https://github.com/dani-garcia/vaultwarden/blob/main/src/static/templates/email/send_org_invite.html.hbs keine {{org_id}} finden, kannst du dir entsprechende Stelle bitte einmal zeigen?

**Comment by WirArbeitenMitHochdruckAnEinerLoesung** [comment]
Hi,

danke für die schnelle Antwort!

Es geht glaube ich um den Link für die Einladung. Das ist die einzige Stelle, wo die "org_id" zu finden ist. Das wäre hier. Der Block hinter {{url}},

**Original:**

```
> <a href="{{url}}"
>             clicktracking=off target="_blank" style="color: #ffffff; text-decoration: none; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; background-color: #3c8dbc; border-color: #3c8dbc; border-style: solid; border-width: 10px 20px; margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; box-sizing: border-box; font-size: 16px; line-height: 25px; -webkit-font-smoothing: antialiased; -webkit-text-size-adjust: none;">
>          Join Organization Now
>          </a>
```

**Deutsches Template:**

```
> <a href="{{url}}**/#/accept-organization/?organizationId={{org_id}}&organizationUserId={{org_user_id}}&email={{email}}&organizationName={{org_name_encoded}}&token={{to>**
>             clicktracking=off target="_blank" style="color: #ffffff; text-decoration: none; text-align: center; cursor: pointer; display: inline-block; border-radius: 5px; ba>
>          Jetzt der Organisation beitreten
>          </a>
```

Danke!

**Comment by kennymc-c** [comment]
Verwendest du die aktuelle Version der Tenplates? Die aktuell deutsche Version sieht so aus und hat nicht den Zusatz nach der url Variable

https://github.com/kennymc-c/vaultwarden-lang-de/blob/main/email/send_org_invite.html.hbs

**Comment by strausmann** [comment]
Wollte ich auch gerade sagen, da steht nur noch {{url}}

https://github.com/strausmann/vaultwarden-lang-de/blob/strausmann-patch-2/email/send_org_invite.html.hbs#L12

**Comment by WirArbeitenMitHochdruckAnEinerLoesung** [comment]
> Verwendest du die aktuelle Version der Tenplates? Die aktuell deutsche Version sieht so aus und hat nicht den Zusatz nach der url Variable
> 
> https://github.com/kennymc-c/vaultwarden-lang-de/blob/main/email/send_org_invite.html.hbs

Gab es zwischendurch ein Update? My bad! Hatte nicht mitbekommen. Werde direkt die aktuelle Version einspielen und mal die Benachrichtigungen zu diesem Template in GitHub aktualisieren.

Danke euch für die schnellen Antworten!

**Comment by kennymc-c** [comment]
Es gibt mit 1.32.3 eine Fix für die Org invite URL in den Templates (https://github.com/dani-garcia/vaultwarden/pull/5100). Eventuell war auch das die Ursache des Problems. Ich habe die Änderungen hier auch gerade übernommen.
