### ISSUE TITLE
Template-Sammlung versionieren

### ISSUE THREAD

**Issue by Crash1602** [kennymc-c/vaultwarden-lang-de#9]
Guten Morgen,

ich hatte heute das Problem, dass meine Email-OTP nicht mehr funktioniert haben. Die Lösung war die Aktualisierung der deutschen Templates. Das es Änderungen gab, habe ich leider nicht mitbekommen und auch nicht daran gedacht den Stand zu einem vorherigen Zeitpunkt zu prüfen.

Daher meine Frage, ob es möglich ist die Template-Sammlung zu versionieren, damit es möglich wird diese zu watchen?

Grüße,
Crash1602

**Comment by kennymc-c** [comment]
Ja, das kann ich zukünftig machen

**Comment by Crash1602** [comment]
Sehr gut, vielen dank.
